In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
iris_df = pd.read_csv('iris.csv') 
iris_df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [5]:
iris_df.isnull().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

In [6]:
iris_df.groupby("variety").variety.count()

variety
Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [7]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [48]:
iris_df.corr()

sepal.length  sepal.width  petal.length  petal.width
sepal.length      1.000000    -0.117570      0.871754     0.817941
sepal.width      -0.117570     1.000000     -0.428440    -0.366126
petal.length      0.871754    -0.428440      1.000000     0.962865
petal.width       0.817941    -0.366126      0.962865     1.000000

petal.width and petal.lengthcorrelation must remove in seconde modelizer

In [49]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression, Perceptron 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.utils import shuffle

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [40]:
iris_df["petal.width"]

0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ... 
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal.width, Length: 150, dtype: float64

In [59]:
X, y = load_iris(return_X_y=True)
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

remove iris_df["petal.width"] from X

In [60]:
X_del = np.delete(X, 3 , 1)
X_del

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4],
       [5.4, 3.9, 1.7],
       [4.6, 3.4, 1.4],
       [5. , 3.4, 1.5],
       [4.4, 2.9, 1.4],
       [4.9, 3.1, 1.5],
       [5.4, 3.7, 1.5],
       [4.8, 3.4, 1.6],
       [4.8, 3. , 1.4],
       [4.3, 3. , 1.1],
       [5.8, 4. , 1.2],
       [5.7, 4.4, 1.5],
       [5.4, 3.9, 1.3],
       [5.1, 3.5, 1.4],
       [5.7, 3.8, 1.7],
       [5.1, 3.8, 1.5],
       [5.4, 3.4, 1.7],
       [5.1, 3.7, 1.5],
       [4.6, 3.6, 1. ],
       [5.1, 3.3, 1.7],
       [4.8, 3.4, 1.9],
       [5. , 3. , 1.6],
       [5. , 3.4, 1.6],
       [5.2, 3.5, 1.5],
       [5.2, 3.4, 1.4],
       [4.7, 3.2, 1.6],
       [4.8, 3.1, 1.6],
       [5.4, 3.4, 1.5],
       [5.2, 4.1, 1.5],
       [5.5, 4.2, 1.4],
       [4.9, 3.1, 1.5],
       [5. , 3.2, 1.2],
       [5.5, 3.5, 1.3],
       [4.9, 3.6, 1.4],
       [4.4, 3. , 1.3],
       [5.1, 3.4, 1.5],
       [5. , 3.5, 1.3],
       [4.5, 2.3

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
X_train_del, X_test_del, y_train_del, y_test_del = train_test_split(X_del, y, test_size=0.5, random_state=0)


In [79]:
gnb = GaussianNB()
perceptron_classifier = Perceptron()
lm_classifier = LogisticRegression(C=2)
knn_clf = KNeighborsClassifier(n_neighbors=3)


In [80]:
gnb_fit = gnb.fit(X_train, y_train)
perceptron_fit = perceptron_classifier.fit(X_train, y_train)
lm_fit = lm_classifier.fit(X_train, y_train)
knn_fit = knn_clf.fit(X_train, y_train)


In [81]:
gnb_pred = gnb_fit.predict(X_test)
perceptron_pred = perceptron_fit.predict(X_test)
lm_pred = lm_fit.predict(X_test)
knn_pred = knn_fit.predict(X_test)



In [82]:
gnb_fit_del = gnb.fit(X_train_del, y_train_del)
perceptron_fit_del = perceptron_classifier.fit(X_train_del, y_train_del)
lm_fit_del = lm_classifier.fit(X_train_del, y_train_del)
knn_fit_del = knn_clf.fit(X_train_del, y_train_del)

In [83]:
gnb_pred_del = gnb_fit_del.predict(X_test_del)
perceptron_pred_del = perceptron_fit_del.predict(X_test_del)
lm_pred_del= lm_fit_del.predict(X_test_del)
knn_pred_del = knn_fit_del.predict(X_test_del)

In [84]:
print("Logistic Regression")
print(classification_report(y_test, lm_pred))
confusion_matrix(y_test, lm_pred)

print("Logistic Regression adter deletion")
print(classification_report(y_test_del, lm_pred_del))
confusion_matrix(y_test_del, lm_pred_del)

Logistic Regression
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.88      0.97      0.92        30
           2       0.95      0.83      0.89        24

    accuracy                           0.93        75
   macro avg       0.94      0.93      0.94        75
weighted avg       0.94      0.93      0.93        75

Logistic Regression adter deletion
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.85      0.97      0.91        30
           2       0.95      0.79      0.86        24

    accuracy                           0.92        75
   macro avg       0.93      0.92      0.92        75
weighted avg       0.93      0.92      0.92        75



array([[21,  0,  0],
       [ 0, 29,  1],
       [ 0,  5, 19]])

In [85]:
print("GaussianNB")
print(classification_report(y_test, gnb_pred))
confusion_matrix(y_test, gnb_pred)

print("GaussianNB after deletion")
print(classification_report(y_test_del, gnb_pred_del))
confusion_matrix(y_test_del, gnb_pred_del)

GaussianNB
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.88      1.00      0.94        30
           2       1.00      0.83      0.91        24

    accuracy                           0.95        75
   macro avg       0.96      0.94      0.95        75
weighted avg       0.95      0.95      0.95        75

GaussianNB after deletion
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.74      0.83      0.78        30
           2       0.75      0.62      0.68        24

    accuracy                           0.81        75
   macro avg       0.83      0.82      0.82        75
weighted avg       0.81      0.81      0.81        75



array([[21,  0,  0],
       [ 0, 25,  5],
       [ 0,  9, 15]])

In [86]:
print("Perceptron")
print(classification_report(y_test, perceptron_pred))
confusion_matrix(y_test, perceptron_pred)

print("Perceptron after deletion")
print(classification_report(y_test_del, perceptron_pred_del))
confusion_matrix(y_test_del, perceptron_pred_del)

Perceptron
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      0.40      0.57        30
           2       0.57      1.00      0.73        24

    accuracy                           0.76        75
   macro avg       0.86      0.80      0.77        75
weighted avg       0.86      0.76      0.74        75

Perceptron after deletion
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.00      0.00      0.00        30
           2       0.44      1.00      0.62        24

    accuracy                           0.60        75
   macro avg       0.48      0.67      0.54        75
weighted avg       0.42      0.60      0.48        75



/home/mhazad/iris/iris_classification_train_models/env/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mhazad/iris/iris_classification_train_models/env/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mhazad/iris/iris_classification_train_models/env/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this 

array([[21,  0,  0],
       [ 0,  0, 30],
       [ 0,  0, 24]])

In [87]:
print("KNN")
print(classification_report(y_test, knn_pred))
confusion_matrix(y_test, knn_pred)

print("KNN after deletion")
print(classification_report(y_test_del, knn_pred_del))
confusion_matrix(y_test_del, knn_pred_del)

KNN
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.88      0.97      0.92        30
           2       0.95      0.83      0.89        24

    accuracy                           0.93        75
   macro avg       0.94      0.93      0.94        75
weighted avg       0.94      0.93      0.93        75

KNN after deletion
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.84      0.87      0.85        30
           2       0.83      0.79      0.81        24

    accuracy                           0.88        75
   macro avg       0.89      0.89      0.89        75
weighted avg       0.88      0.88      0.88        75



array([[21,  0,  0],
       [ 0, 26,  4],
       [ 0,  5, 19]])